"""
generate_ini_force_cfe.py
==========================
Generuje plik .ini z FORCE COVER na CFE - czyli MUT NADPISZE bootloader.

Standardowy generate_ini_file.py tworzy linie:
   PARTITIONS=CFE,0x00000000-0x0000FFFF,uncover|kernelfs,0x00010000-0x003FFFFF,cover
                                       ^^^^^^^^
                                       NIE FLASHUJ CFE

Ten skrypt zmienia uncover na cover, dzieki czemu MUT FAKTYCZNIE
nadpisuje partycje CFE (bootloader) - co jest niezbedne gdy CFE
jest popsuty i blokuje boot kazdego nowego kernelfs.

Uzycie:
    python generate_ini_force_cfe.py <plik.bin>

Tworzy plik <plik>_FORCE_CFE.ini obok bin'a (i .ini.bak ze starym).
"""

import zlib
import os
import sys
import shutil


def calculate_crc(content_bytes):
    return zlib.crc32(content_bytes) & 0xFFFFFFFF


def process_firmware_file(file_path):
    with open(file_path, 'rb') as f:
        file_content = f.read()
    return len(file_content), calculate_crc(file_content)


def generate_ini_content(filename, filesize, firmware_crc):
    # FORCE COVER na CFE: zmienione 'uncover' -> 'cover' zeby MUT
    # faktycznie nadpisal bootloader (a nie tylko go pokazal w GUI).
    # Format ZGODNY 1:1 z oryginalnym generate_ini_file.py - tylko jedna roznica:
    # flaga CFE zmieniona z 'uncover' na 'cover'.
    content = (
        "# autogenerated by tools\n"
        "# do NOT modify this file\n"
        f"IMAGE_NAME={filename}\n"
        f"IMAGE_SIZE={filesize}\n"
        "PACKAGE_ID=fnt-HGW\n"
        "PRODUCT_ID=fnt-HGW\n"
        "FIRMWARE_VERSION=0\n"
        "PCB_VERSION=0\n"
        f"FIRMWARE_CRC_SUM={firmware_crc}\n"
        "PARTITIONS=CFE,0x00000000-0x0000FFFF,cover|kernelfs,0x00010000-0x003FFFFF,cover\n"
        "INI_CRC_SUM="
    )
    # CRC obliczane jest dla calej tresci ZA WYJATKIEM samej liczby po INI_CRC_SUM=
    # czyli dla content konczacego sie wlasnie na "INI_CRC_SUM=" (bez liczby)
    ini_crc = calculate_crc(content.encode('ascii'))
    content += str(ini_crc)
    return content


def main():
    if len(sys.argv) != 2:
        print("Usage: python generate_ini_force_cfe.py <firmware.bin>")
        sys.exit(1)

    firmware_file = sys.argv[1]
    if not os.path.isfile(firmware_file):
        print(f"ERROR: file not found: {firmware_file}")
        sys.exit(1)

    filename = os.path.basename(firmware_file)
    base_name = os.path.splitext(filename)[0]
    folder = os.path.dirname(firmware_file) or '.'

    print(f"[*] Processing {filename}...")
    filesize, firmware_crc = process_firmware_file(firmware_file)
    print(f"    Size: {filesize} bytes")
    print(f"    CRC32: {firmware_crc}")

    ini_content = generate_ini_content(filename, filesize, firmware_crc)

    # Zapis NADPISUJACY oryginalny .ini (backup ze starym)
    original_ini = os.path.join(folder, f"{base_name}.ini")
    if os.path.isfile(original_ini):
        backup = original_ini + ".uncover_backup"
        if not os.path.isfile(backup):
            shutil.copy2(original_ini, backup)
            print(f"[*] Backup of original INI: {os.path.basename(backup)}")

    with open(original_ini, 'w', newline='\n', encoding='ascii') as f:
        f.write(ini_content)

    print(f"[+] FORCE-CFE .ini written to: {os.path.basename(original_ini)}")
    print()
    print("Content:")
    print("-" * 60)
    print(ini_content)
    print("-" * 60)
    print()
    print("[!] Now run HuaweiMUT.exe and pick this .bin - MUT will load")
    print("    matching .ini AUTOMATICALLY. In 'Cover partitions' you should")
    print("    see BOTH CFE and kernelfs as checkable. Tick BOTH. Start flash.")


if __name__ == "__main__":
    main()
