#!/usr/bin/env python3
"""
mut_python.py - Python replika HuaweiMUT.exe (WS7200/AX3/Honor Router 3)

Reverse-engineered z HuaweiMUT.exe (389120 bytes, VC7-14 MFC, multicast UDP).
Funkcje zreversowane (IDA Pro + Hex-Rays):
    sub_402260  - OnButtonStart() handler (UI)
    sub_41FD40  - INI parser + INI_CRC_SUM check (sets dword_460E24)
    sub_41F2F0  - main send loop (UDP multicast)
    sub_4202F0  - packet builder (1086 bytes: 62 header + 1024 data)
    sub_41F0A0  - socket setup
    sub_41F8E0  - firmware CRC32 calculator (zlib-compatible)
    sub_420480  - CRC32 (zlib)
    sub_41F6D0  - adapter IP lookup (GetAdaptersInfo)
    sub_41F820  - precise sleep (QueryPerformanceCounter)
    sub_41F960  - file chunk read (fseek+fread)

PACKET FORMAT (1086 bytes):
    [0..3]    4   control_word    = (opcode << 29) | 0x00000400
                                    DATA = 0x20000400
                                    LAST = 0x40000400
                                    INIT = 0x80000400
    [4..7]    4   chunk_counter   sequence (uint32 LE)
    [8..11]   4   chunk_crc32     CRC32 of (padded to 1024) chunk
    [12..15]  4   total_file_size uint32 LE
    [16..19]  4   firmware_crc32  FIRMWARE_CRC_SUM (z INI)
    [20..39]  20  PACKAGE_ID      ASCII, null-padded
    [40..41]  2   unknown_word    (z byte_46568E[4166])
    [42..61]  20  PRODUCT_ID      ASCII, null-padded
    [62..1085] 1024 chunk_data    firmware chunk, null-padded if shorter

SOCKET CONFIG (sub_41F0A0):
    socket(AF_INET, SOCK_DGRAM, 0)
    SO_BROADCAST = 1
    bind(PC_IP, 13456)              <- SOURCE PORT = 13456!
    IP_ADD_MEMBERSHIP(224.0.0.119, PC_IF)
    IP_MULTICAST_LOOP = 1
    IP_MULTICAST_TTL = 0            <- local network ONLY
    IP_MULTICAST_IF = PC_IP
"""

import argparse
import os
import shutil
import socket
import struct
import subprocess
import sys
import threading
import time
import zlib
from pathlib import Path

# ============================================================================
# STAŁE z reverse engineering
# ============================================================================
MULTICAST_IP        = "224.0.0.119"
MULTICAST_PORT      = 13456          # 0x3490
PACKET_SIZE         = 1086
CHUNK_SIZE          = 1024           # 0x400
HEADER_SIZE         = 62             # 1086 - 1024
DEFAULT_INTERVAL_MS = 200

OPCODE_DATA = 1                      # data chunk (1024 bytes)
OPCODE_LAST = 2                      # last chunk (< 1024 bytes)
OPCODE_INIT = 4                      # init/partition table

# Control word values (per sub_4202F0)
CTRL_DATA = (OPCODE_DATA << 29) | 0x00000400  # 0x20000400
CTRL_LAST = (OPCODE_LAST << 29) | 0x00000400  # 0x40000400
CTRL_INIT = (OPCODE_INIT << 29) | 0x00000400  # 0x80000400

# Default INI fields (z generate_ini_file.py + generate_ini_force_cfe.py)
DEFAULT_PACKAGE_ID       = "fnt-HGW"
DEFAULT_PRODUCT_ID       = "fnt-HGW"
DEFAULT_FIRMWARE_VERSION = "0"
DEFAULT_PCB_VERSION      = "0"
PARTITIONS_NORMAL    = "CFE,0x00000000-0x0000FFFF,uncover|kernelfs,0x00010000-0x003FFFFF,cover"
PARTITIONS_FORCE_CFE = "CFE,0x00000000-0x0000FFFF,cover|kernelfs,0x00010000-0x003FFFFF,cover"


# ============================================================================
# Helpers
# ============================================================================
def crc32(data: bytes) -> int:
    """Identycznie jak sub_420480 (potwierdzone - generate_ini_file.py używa zlib i działa)."""
    return zlib.crc32(data) & 0xFFFFFFFF


# ============================================================================
# INI Generation (skopiowane z generate_ini_file.py + generate_ini_force_cfe.py;
# tamte pliki POZOSTAJĄ NIETKNIĘTE - to kopia inline dla all-in-one tool)
# ============================================================================
def process_firmware_file(file_path: str):
    """Returns (file_size, file_crc32). Identyczne z generate_ini_file.py."""
    with open(file_path, 'rb') as f:
        data = f.read()
    return len(data), crc32(data)


def generate_ini_content(filename: str, filesize: int, firmware_crc: int,
                         force_cfe: bool = False,
                         package_id: str = DEFAULT_PACKAGE_ID,
                         product_id: str = DEFAULT_PRODUCT_ID,
                         firmware_version: str = DEFAULT_FIRMWARE_VERSION,
                         pcb_version: str = DEFAULT_PCB_VERSION) -> str:
    """Generuje content INI z poprawnym INI_CRC_SUM (zlib CRC32)."""
    partitions = PARTITIONS_FORCE_CFE if force_cfe else PARTITIONS_NORMAL
    content = (
        "# autogenerated by tools\n"
        "# do NOT modify this file\n"
        f"IMAGE_NAME={filename}\n"
        f"IMAGE_SIZE={filesize}\n"
        f"PACKAGE_ID={package_id}\n"
        f"PRODUCT_ID={product_id}\n"
        f"FIRMWARE_VERSION={firmware_version}\n"
        f"PCB_VERSION={pcb_version}\n"
        f"FIRMWARE_CRC_SUM={firmware_crc}\n"
        f"PARTITIONS={partitions}\n"
        "INI_CRC_SUM="
    )
    ini_crc = crc32(content.encode('ascii'))
    content += str(ini_crc)
    return content


def generate_ini_for_firmware(firmware_path: str, force_cfe: bool = False,
                              ini_path: str = None, backup: bool = True) -> str:
    """Stwórz .ini obok firmware'u. Zwraca path do .ini."""
    filename = os.path.basename(firmware_path)
    folder = os.path.dirname(firmware_path) or '.'
    base = os.path.splitext(filename)[0]
    if ini_path is None:
        ini_path = os.path.join(folder, f"{base}.ini")

    filesize, fw_crc = process_firmware_file(firmware_path)

    if backup and os.path.isfile(ini_path):
        bak = ini_path + ".bak"
        if not os.path.isfile(bak):
            shutil.copy2(ini_path, bak)
            print(f"[INI] Backup oryginalu: {os.path.basename(bak)}")

    content = generate_ini_content(filename, filesize, fw_crc, force_cfe=force_cfe)
    with open(ini_path, 'w', newline='\n', encoding='ascii') as f:
        f.write(content)

    mode = "FORCE-CFE (CFE+kernelfs cover)" if force_cfe else "normalny (CFE uncover)"
    print(f"[INI] Wygenerowano [{mode}]: {ini_path}")
    print(f"      Size:    {filesize:,} bytes")
    print(f"      CRC32:   {fw_crc} (0x{fw_crc:08X})")
    return ini_path


# ============================================================================
# Network adapter helpers (replika sub_41F6D0 + auto-detect)
# ============================================================================
def list_network_adapters() -> list:
    """Lista kart sieciowych Windows z IPv4. Returns [{name, ip, is_wifi}, ...]."""
    adapters = []
    try:
        result = subprocess.run(['ipconfig'], capture_output=True, text=True,
                                encoding='cp852', errors='replace', timeout=5)
        current = None
        for line in result.stdout.splitlines():
            # Header karty (linia nie zaczyna sie spacja i kończy ':')
            if line and not line.startswith(' ') and not line.startswith('\t') and line.rstrip().endswith(':'):
                current = line.strip().rstrip(':').strip()
            elif 'IPv4' in line and ':' in line:
                ip = line.split(':', 1)[1].strip()
                ip = ip.replace('(Preferred)', '').replace('(Preferowane)', '').strip()
                if ip and current and not ip.startswith('169.254.'):
                    is_wifi = bool(
                        'wireless' in current.lower()
                        or 'wi-fi' in current.lower()
                        or 'wifi' in current.lower()
                        or 'bezprzewod' in current.lower()
                    )
                    adapters.append({'name': current, 'ip': ip, 'is_wifi': is_wifi})
    except Exception as e:
        print(f"[WARN] ipconfig failed: {e}", file=sys.stderr)

    # Fallback: gethostbyname_ex
    if not adapters:
        try:
            _, _, ips = socket.gethostbyname_ex(socket.gethostname())
            for ip in ips:
                if not ip.startswith('127.') and not ip.startswith('169.254.'):
                    adapters.append({'name': 'host', 'ip': ip, 'is_wifi': False})
        except Exception:
            pass
    return adapters


def adapter_for_ip(ip: str) -> dict:
    """Zwraca info o adapterze dla danego IP, lub None."""
    for a in list_network_adapters():
        if a['ip'] == ip:
            return a
    return None


def router_is_alive(ip: str = '192.168.1.1', timeout_ms: int = 1000) -> bool:
    """Ping na router. True = router odpowiada (PROBLEM dla unbrick'a!)."""
    try:
        result = subprocess.run(
            ['ping', '-n', '1', '-w', str(timeout_ms), ip],
            capture_output=True, text=True, timeout=timeout_ms / 1000.0 + 2
        )
        return result.returncode == 0 and ('TTL=' in result.stdout or 'ttl=' in result.stdout)
    except Exception:
        return False


def auto_detect_pc_ip(prefer: str = '192.168.1.') -> str:
    """Znajdz IP karty - preferuj 192.168.1.x, potem 192.168.x.x, potem cokolwiek."""
    adapters = list_network_adapters()
    for a in adapters:
        if a['ip'].startswith(prefer):
            return a['ip']
    for a in adapters:
        if a['ip'].startswith('192.168.'):
            return a['ip']
    for a in adapters:
        if not a['ip'].startswith('127.'):
            return a['ip']
    return None


def validate_pc_ip(pc_ip: str) -> bool:
    """Sprawdź czy pc_ip istnieje na ktorymkolwiek adapterze."""
    if not pc_ip:
        return False
    return any(a['ip'] == pc_ip for a in list_network_adapters())


def precise_sleep(ms: int) -> None:
    """Replika sub_41F820 (QueryPerformanceCounter busy-wait)."""
    if ms <= 0:
        return
    target = time.perf_counter() + ms / 1000.0
    while time.perf_counter() < target:
        if ms >= 100:
            time.sleep(0.001)


def parse_ini(ini_path: Path) -> dict:
    """Parsuje INI w stylu sub_41FD40 (key=value, ignore comments)."""
    fields = {}
    with open(ini_path, 'rb') as f:
        content = f.read()
    # Both \r\n and \n line endings (sub_41FD40 czyta jako binary)
    for raw_line in content.replace(b'\r\n', b'\n').split(b'\n'):
        line = raw_line.strip()
        if not line or line.startswith(b'#') or line.startswith(b'//'):
            continue
        if b'=' not in line:
            continue
        key, _, val = line.partition(b'=')
        fields[key.decode('ascii', errors='replace').strip()] = val.decode('ascii', errors='replace').strip()
    return fields


def parse_partitions(partitions_str: str) -> list:
    """Parsuje 'CFE,0x0-0xFFFF,uncover|kernelfs,0x10000-0x3FFFFF,cover'."""
    partitions = []
    if not partitions_str:
        return partitions
    for entry in partitions_str.split('|'):
        parts = entry.split(',')
        if len(parts) < 3:
            continue
        name = parts[0]
        range_str = parts[1]
        flag = parts[2]
        if '-' not in range_str:
            continue
        start_str, end_str = range_str.split('-', 1)
        try:
            start = int(start_str, 16) if start_str.startswith('0x') else int(start_str)
            end = int(end_str, 16) if end_str.startswith('0x') else int(end_str)
        except ValueError:
            continue
        partitions.append({
            'name': name,
            'start': start,
            'end': end,
            'flag': flag,
            'cover': flag.lower() == 'cover',
        })
    return partitions


# ============================================================================
# Packet builder (replika sub_4202F0)
# ============================================================================
def build_packet(opcode: int,
                 chunk_data: bytes,
                 chunk_counter: int,
                 total_size: int,
                 firmware_crc: int,
                 package_id: str,
                 product_id: str,
                 pcb_word: int = 0) -> bytes:
    """
    Buduje 1086-bajtowy packet zgodnie z sub_4202F0.

    Args:
        opcode:        OPCODE_DATA=1, OPCODE_LAST=2, OPCODE_INIT=4
        chunk_data:    do 1024 bajtów payload (zostanie null-padded)
        chunk_counter: sequence number (dword_45E1BC)
        total_size:    całkowity rozmiar pliku firmware
        firmware_crc:  FIRMWARE_CRC_SUM z .ini (CRC całego pliku)
        package_id:    z INI (max 20 bajtów po obcięciu)
        product_id:    z INI (max 20 bajtów po obcięciu)
        pcb_word:      WORD na offset 40-41 (z byte_46568E[4166])
    """
    if len(chunk_data) > CHUNK_SIZE:
        raise ValueError(f"chunk_data too long: {len(chunk_data)} > {CHUNK_SIZE}")

    # Pad chunk to 1024 bytes
    chunk_padded = chunk_data + b'\x00' * (CHUNK_SIZE - len(chunk_data))

    # CRC32 zawsze na 1024 bajtach (per sub_4202F0: sub_420480(&Destination[42], 1024))
    chunk_crc = crc32(chunk_padded)

    # Control word: opcode<<29 | 0x0400
    control_word = (opcode << 29) | 0x00000400

    # PACKAGE_ID padding (20 bytes)
    pkg_bytes = package_id.encode('ascii', errors='replace')[:20]
    pkg_padded = pkg_bytes + b'\x00' * (20 - len(pkg_bytes))

    # PRODUCT_ID padding (20 bytes)
    prod_bytes = product_id.encode('ascii', errors='replace')[:20]
    prod_padded = prod_bytes + b'\x00' * (20 - len(prod_bytes))

    # Header (62 bytes)
    header = struct.pack('<I', control_word)          # [0..3]
    header += struct.pack('<I', chunk_counter)        # [4..7]
    header += struct.pack('<I', chunk_crc)            # [8..11]
    header += struct.pack('<I', total_size)           # [12..15]
    header += struct.pack('<I', firmware_crc)         # [16..19]
    header += pkg_padded                               # [20..39]
    header += struct.pack('<H', pcb_word & 0xFFFF)    # [40..41]
    header += prod_padded                              # [42..61]

    assert len(header) == HEADER_SIZE, f"Header size {len(header)} != {HEADER_SIZE}"

    packet = header + chunk_padded
    assert len(packet) == PACKET_SIZE, f"Packet size {len(packet)} != {PACKET_SIZE}"

    return packet


def build_init_payload(partitions: list) -> bytes:
    """
    Buduje 1024-byte payload dla INIT packet (opcode 4).
    Format z sub_41F2F0 partition loop:
        for each partition:
            qmemcpy(v5 - 5, v6, 0x14);   // 20 bytes (name+meta?)
            *v5 = start_offset            // 4 bytes
            v5[1] = end_offset            // 4 bytes
            *(BYTE*)(v5+2) = cover ? 2 : 1  // 1 byte (uncover=1, cover=2)
            v5 += 8 dword (= 32 bytes)    // padding 3 bytes
    """
    payload = b''
    for p in partitions:
        # Name (20 bytes, null-padded)
        name_bytes = p['name'].encode('ascii', errors='replace')[:20]
        name_padded = name_bytes + b'\x00' * (20 - len(name_bytes))
        payload += name_padded
        # Start, End offsets
        payload += struct.pack('<II', p['start'] & 0xFFFFFFFF, p['end'] & 0xFFFFFFFF)
        # Cover flag (cover=2, uncover=1)
        payload += b'\x02' if p['cover'] else b'\x01'
        # Padding (3 bytes to reach 32-byte total per partition)
        payload += b'\x00\x00\x00'
    return payload


# ============================================================================
# MUT class
# ============================================================================
class MUT:
    def __init__(self,
                 firmware_path: str,
                 ini_path: str,
                 pc_ip: str,
                 dest_ip: str = MULTICAST_IP,
                 port: int = MULTICAST_PORT,
                 interval_ms: int = DEFAULT_INTERVAL_MS,
                 use_multicast: bool = True,
                 ttl: int = 0,
                 verbose: bool = False,
                 log_hex: bool = False,
                 listen: bool = False,
                 max_passes: int = 0):
        self.firmware_path = firmware_path
        self.ini_path = ini_path
        self.pc_ip = pc_ip
        self.dest_ip = dest_ip
        self.port = port
        self.interval_ms = interval_ms
        self.use_multicast = use_multicast
        self.ttl = ttl
        self.verbose = verbose
        self.log_hex = log_hex
        self.listen = listen
        self.max_passes = max_passes

        # Load INI
        self.fields = parse_ini(Path(ini_path))
        self.package_id = self.fields.get('PACKAGE_ID', '')
        self.product_id = self.fields.get('PRODUCT_ID', '')
        self.partitions = parse_partitions(self.fields.get('PARTITIONS', ''))

        # Validate required fields
        required = ['IMAGE_NAME', 'IMAGE_SIZE', 'PACKAGE_ID', 'PRODUCT_ID',
                    'FIRMWARE_VERSION', 'PCB_VERSION', 'FIRMWARE_CRC_SUM',
                    'INI_CRC_SUM', 'PARTITIONS']
        missing = [k for k in required if not self.fields.get(k)]
        if missing:
            print(f"[WARN] Missing INI fields: {missing}", file=sys.stderr)

        # Load firmware
        with open(firmware_path, 'rb') as f:
            self.firmware_data = f.read()
        self.file_size = len(self.firmware_data)
        self.firmware_crc = crc32(self.firmware_data)

        # Verify CRC matches INI
        ini_fw_crc = int(self.fields.get('FIRMWARE_CRC_SUM', '0'))
        if ini_fw_crc != self.firmware_crc:
            print(f"[WARN] Firmware CRC mismatch! Calc={self.firmware_crc} INI={ini_fw_crc}", file=sys.stderr)

        # Stats
        self.passes_completed = 0
        self.packets_sent = 0
        self.bytes_sent = 0
        self.running = False
        self.responses = []

    def setup_socket(self) -> socket.socket:
        """Replika sub_41F0A0. Bind robust dla WinError 10049."""
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, 0)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        # Bind source port = 13456 (per sub_41F0A0)
        # Defensive: jezeli pc_ip nie istnieje na karcie -> fallback na 0.0.0.0
        bind_ip = self.pc_ip
        try:
            s.bind((bind_ip, self.port))
        except OSError as e:
            if e.winerror == 10049 if hasattr(e, 'winerror') else False:
                print(f"[WARN] IP {self.pc_ip} nie istnieje na karcie - bind 0.0.0.0:{self.port}", file=sys.stderr)
            else:
                print(f"[WARN] bind({bind_ip}:{self.port}) failed: {e} - retry 0.0.0.0", file=sys.stderr)
            s.bind(('0.0.0.0', self.port))

        if self.use_multicast:
            # IP_ADD_MEMBERSHIP
            mreq = socket.inet_aton(self.dest_ip) + socket.inet_aton(self.pc_ip)
            try:
                s.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
            except OSError as e:
                print(f"[WARN] IP_ADD_MEMBERSHIP failed: {e}", file=sys.stderr)
            # IP_MULTICAST_LOOP = 1
            s.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_LOOP, 1)
            # IP_MULTICAST_TTL (default 0 = local only, per MUT)
            s.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, self.ttl)
            # IP_MULTICAST_IF = PC interface
            s.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton(self.pc_ip))

        s.settimeout(0.001)  # for non-blocking recv
        return s

    def listen_thread(self, sock: socket.socket):
        """Listen for router responses on the same socket."""
        print("[LISTEN] Starting response listener...")
        while self.running:
            try:
                data, addr = sock.recvfrom(4096)
                self.responses.append((time.time(), addr, data))
                print(f"\n[*** RESPONSE FROM ROUTER ***] {addr} ({len(data)} bytes)")
                print(f"  Hex: {data[:64].hex()}{'...' if len(data) > 64 else ''}")
            except socket.timeout:
                continue
            except OSError:
                break

    def send_loop(self):
        """Main send loop per sub_41F2F0."""
        sock = self.setup_socket()
        dest = (self.dest_ip, self.port)

        self.running = True

        if self.listen:
            listener = threading.Thread(target=self.listen_thread, args=(sock,), daemon=True)
            listener.start()

        try:
            while self.running:
                self._send_one_pass(sock, dest)
                self.passes_completed += 1
                print(f"\n=== PASS {self.passes_completed} COMPLETE ({self.packets_sent} pkts, "
                      f"{self.bytes_sent/1024/1024:.2f} MB sent so far) ===\n")
                if self.max_passes and self.passes_completed >= self.max_passes:
                    print(f"Reached max_passes={self.max_passes}, stopping.")
                    break
                precise_sleep(self.interval_ms * 2)
        except KeyboardInterrupt:
            print("\n[CTRL+C] Stopping...")
        finally:
            self.running = False
            sock.close()

    def _send_one_pass(self, sock, dest):
        """Single pass: INIT + DATA*N + LAST."""
        chunk_counter = 0

        # 1. INIT packet (opcode 4) with partition table
        init_payload = build_init_payload(self.partitions)
        init_packet = build_packet(
            opcode=OPCODE_INIT,
            chunk_data=init_payload,
            chunk_counter=chunk_counter,
            total_size=self.file_size,
            firmware_crc=self.firmware_crc,
            package_id=self.package_id,
            product_id=self.product_id,
        )
        self._send_packet(sock, init_packet, dest, 'INIT', chunk_counter, 0)
        chunk_counter += 1
        precise_sleep(self.interval_ms)

        if not self.running:
            return

        # 2. DATA + LAST packets
        offset = 0
        while offset < self.file_size and self.running:
            remaining = self.file_size - offset
            if remaining <= CHUNK_SIZE:
                # LAST packet (opcode 2)
                chunk_data = self.firmware_data[offset:offset + remaining]
                packet = build_packet(
                    opcode=OPCODE_LAST,
                    chunk_data=chunk_data,
                    chunk_counter=chunk_counter,
                    total_size=self.file_size,
                    firmware_crc=self.firmware_crc,
                    package_id=self.package_id,
                    product_id=self.product_id,
                )
                self._send_packet(sock, packet, dest, 'LAST', chunk_counter, offset)
                break
            else:
                # DATA packet (opcode 1)
                chunk_data = self.firmware_data[offset:offset + CHUNK_SIZE]
                packet = build_packet(
                    opcode=OPCODE_DATA,
                    chunk_data=chunk_data,
                    chunk_counter=chunk_counter,
                    total_size=self.file_size,
                    firmware_crc=self.firmware_crc,
                    package_id=self.package_id,
                    product_id=self.product_id,
                )
                self._send_packet(sock, packet, dest, 'DATA', chunk_counter, offset)
                offset += CHUNK_SIZE
                chunk_counter += 1
                precise_sleep(self.interval_ms)

    def _send_packet(self, sock, packet, dest, label, seq, offset):
        try:
            sent = sock.sendto(packet, dest)
            self.packets_sent += 1
            self.bytes_sent += sent
            if self.verbose:
                pct = (offset / self.file_size * 100) if self.file_size else 0
                print(f"[#{self.packets_sent:6d}] {label:4s} seq={seq:6d} "
                      f"off={offset:8d}/{self.file_size} ({pct:5.1f}%)")
            if self.log_hex:
                print(f"  Header: {packet[:HEADER_SIZE].hex()}")
        except OSError as e:
            print(f"[ERROR] sendto failed: {e}", file=sys.stderr)
            self.running = False


# ============================================================================
# CLI
# ============================================================================
def main():
    parser = argparse.ArgumentParser(
        description='Python MUT all-in-one - replika HuaweiMUT.exe dla WS7200/AX3',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
PRZYKLADY UZYCIA:

  Lista dostepnych kart sieciowych:
    python mut_python.py --list-adapters

  Tylko wygeneruj INI (zastapi generate_ini_file.py):
    python mut_python.py firmware.bin --gen-ini

  Wygeneruj INI z CFE COVER (recovery cegly, zastapi generate_ini_force_cfe.py):
    python mut_python.py firmware.bin --gen-ini --force-cfe

  Standardowy multicast z auto-detected IP karty:
    python mut_python.py firmware.bin -v

  Standardowy multicast (jak oryginalny MUT):
    python mut_python.py firmware.bin --pc-ip 192.168.1.5

  Recovery cegly: regeneruj INI z CFE cover + wyslij:
    python mut_python.py firmware.bin --force-cfe -v

  Verbose + hex dump headerow (debugging):
    python mut_python.py firmware.bin --pc-ip 192.168.1.5 -v --hex

  Eksperyment: unicast bezposrednio na router 192.168.1.1:
    python mut_python.py firmware.bin --pc-ip 192.168.1.5 --unicast 192.168.1.1

  Wolniejszy interval (mniej obciaza router):
    python mut_python.py firmware.bin --pc-ip 192.168.1.5 --interval 500

  Z odbiorem odpowiedzi (sprawdza czy router cos zwraca):
    python mut_python.py firmware.bin --pc-ip 192.168.1.5 --listen

  Stop po N pelnych przejsciach (1 przejscie = caly plik wyslany):
    python mut_python.py firmware.bin --pc-ip 192.168.1.5 --passes 10

UWAGA: Musisz uruchomic jako Administrator (bind port 13456).
PRZED URUCHOMIENIEM: ustaw IP karty Ethernet w Windowsie:
    Set-NetIPAddress -InterfaceAlias 'Ethernet' -IPAddress 192.168.1.5 -PrefixLength 24
Lub uruchom: _unbrick_wizard.ps1 / unbrick_all.ps1 (interaktywny wizard).
""")

    parser.add_argument('firmware', nargs='?', help='Plik .bin firmware')
    parser.add_argument('--ini', help='Plik .ini (default: same name jako firmware)')
    parser.add_argument('--pc-ip', help='IP karty PC (np. 192.168.1.5). BRAK = auto-detect.')
    parser.add_argument('--auto-ip', action='store_true', help='Auto-detect IP karty (preferuje 192.168.1.x)')
    parser.add_argument('--list-adapters', action='store_true', help='Pokaz dostepne karty sieciowe i wyjdz')
    parser.add_argument('--gen-ini', action='store_true', help='Tylko wygeneruj .ini z .bin i wyjdz (bez wysylki)')
    parser.add_argument('--force-cfe', action='store_true',
                        help='Wygeneruj .ini z CFE=COVER (nadpisuj bootloader, dla recovery cegly)')
    parser.add_argument('--multicast-ip', default=MULTICAST_IP, help=f'IP multicast (default: {MULTICAST_IP})')
    parser.add_argument('--unicast', help='Wyslij na konkretny IP zamiast multicast (np. 192.168.1.1)')
    parser.add_argument('--port', type=int, default=MULTICAST_PORT, help=f'Port UDP (default: {MULTICAST_PORT})')
    parser.add_argument('--interval', type=int, default=DEFAULT_INTERVAL_MS,
                        help=f'Interval ms miedzy packetami (default: {DEFAULT_INTERVAL_MS})')
    parser.add_argument('--ttl', type=int, default=0,
                        help='IP_MULTICAST_TTL (default: 0=local; sprobuj 1 jak nie dziala)')
    parser.add_argument('--passes', type=int, default=0, help='Stop po N pelnych przejsciach (0=infinite)')
    parser.add_argument('-v', '--verbose', action='store_true', help='Log kazdego packetu')
    parser.add_argument('--hex', action='store_true', help='Hex dump headerow')
    parser.add_argument('--listen', action='store_true',
                        help='Sluchaj odpowiedzi od routera (recvfrom na tym samym sockecie)')
    parser.add_argument('--allow-wifi', action='store_true',
                        help='Pozwol uzywac karty WiFi (NIEZALECANE - moze wyslac pakiety do innego routera)')
    parser.add_argument('--yes', '-y', action='store_true',
                        help='Pomin wszystkie potwierdzenia (DANGEROUS - tylko jak wiesz co robisz)')

    args = parser.parse_args()

    # --- TRYB: list-adapters (no firmware needed) ---
    if args.list_adapters:
        print("=" * 60)
        print("  Dostepne karty sieciowe (IPv4)")
        print("=" * 60)
        adapters = list_network_adapters()
        if not adapters:
            print("  [BLAD] Nie znaleziono zadnej karty z IPv4.")
            sys.exit(1)
        for i, a in enumerate(adapters):
            mark = ' <-- mozesz uzyc --pc-ip ' + a['ip'] if a['ip'].startswith('192.168.') else ''
            print(f"  [{i}] {a['ip']:18s} {a['name']}{mark}")
        auto = auto_detect_pc_ip()
        if auto:
            print(f"\nAuto-detect (--auto-ip) wybralby: {auto}")
        sys.exit(0)

    # Od tego momentu firmware jest wymagany
    if not args.firmware:
        parser.error("Argument 'firmware' jest wymagany (chyba ze --list-adapters)")

    if not Path(args.firmware).exists():
        print(f"[BLAD] Plik firmware nie istnieje: {args.firmware}", file=sys.stderr)
        sys.exit(1)

    if not args.ini:
        args.ini = str(Path(args.firmware).with_suffix('.ini'))

    # --- TRYB: gen-ini (no send) ---
    if args.gen_ini or args.force_cfe and not Path(args.ini).exists():
        ini = generate_ini_for_firmware(args.firmware, force_cfe=args.force_cfe, ini_path=args.ini)
        if args.gen_ini:
            print(f"\n[OK] INI gotowy: {ini}")
            sys.exit(0)

    # --- TRYB: force-cfe (zawsze regeneruj nawet jak istnieje) ---
    if args.force_cfe and not args.gen_ini:
        generate_ini_for_firmware(args.firmware, force_cfe=True, ini_path=args.ini)

    if not Path(args.ini).exists():
        print(f"[BLAD] Plik INI nie istnieje: {args.ini}", file=sys.stderr)
        print(f"       Uzyj --gen-ini aby go wygenerowac, lub --force-cfe dla CFE cover.", file=sys.stderr)
        sys.exit(1)

    # --- Auto-detect PC IP jezeli brak --pc-ip lub --auto-ip ---
    if not args.pc_ip or args.auto_ip:
        detected = auto_detect_pc_ip()
        if detected:
            if args.pc_ip and args.pc_ip != detected:
                print(f"[INFO] Auto-IP override: {args.pc_ip} -> {detected}")
            args.pc_ip = detected
            print(f"[AUTO-IP] Wykryto IP karty: {args.pc_ip}")
        elif not args.pc_ip:
            print("[BLAD] Nie wykryto karty 192.168.x.x. Podaj --pc-ip lub uzyj --list-adapters.", file=sys.stderr)
            sys.exit(1)

    # --- Walidacja: czy --pc-ip istnieje na karcie ---
    if not validate_pc_ip(args.pc_ip):
        print(f"[OSTRZEZENIE] IP {args.pc_ip} nie istnieje na zadnej karcie sieciowej!", file=sys.stderr)
        print(f"              Dostepne IP:", file=sys.stderr)
        for a in list_network_adapters():
            print(f"                {a['ip']:18s} {a['name']}", file=sys.stderr)
        print(f"", file=sys.stderr)
        print(f"Wybierz JEDNA z tych opcji:", file=sys.stderr)
        print(f"  1. Ustaw IP karty w Windowsie (np. Set-NetIPAddress -InterfaceAlias 'Ethernet' -IPAddress {args.pc_ip} -PrefixLength 24)", file=sys.stderr)
        print(f"  2. Uzyj --pc-ip ktoregos z powyzszych IP", file=sys.stderr)
        print(f"  3. Uzyj --auto-ip aby wybrac automatycznie", file=sys.stderr)
        print(f"  4. Skrypt sprobuje bind 0.0.0.0 jako fallback (moze nie dzialac dla multicast)", file=sys.stderr)
        print(f"", file=sys.stderr)
        try:
            ans = input("Kontynuowac mimo to (bind 0.0.0.0)? [t/N]: ").strip().lower()
        except EOFError:
            ans = 'n'
        if ans not in ('t', 'tak', 'y', 'yes'):
            sys.exit(1)

    # === SAFETY CHECKS przed wyslaniem czegokolwiek ===
    adapter = adapter_for_ip(args.pc_ip)

    # SAFETY 1: WiFi adapter detection
    if adapter and adapter.get('is_wifi'):
        print("")
        print("!!! " + "=" * 56 + " !!!")
        print("!!! UWAGA: Wybrales karte WiFi! NIEBEZPIECZNE!         !!!")
        print("!!! " + "=" * 56 + " !!!")
        print(f"  Karta:  {adapter['name']}")
        print(f"  IP:     {adapter['ip']}")
        print("")
        print("  Pakiety multicast pojda do Twojej domowej sieci WiFi,")
        print("  a NIE do routera-cegly Huawei!")
        print("  Router-cegla w trybie upgrade NIE MA WiFi - tylko port LAN.")
        print("")
        print("  PRZED prawdziwym flashowaniem zrob:")
        print("   1. WYLACZ WiFi w Windowsie (lub skrypt unbrick_all.ps1 zrobi to za Ciebie)")
        print("   2. Podpiac kabel Ethernet z laptopa do portu LAN routera-cegly")
        print("   3. Wprowadz router-cegle w tryb upgrade (przycisk H + zasilanie)")
        print("   4. Ustaw Ethernet IP na 192.168.1.5")
        print("")
        if not args.allow_wifi and not args.yes:
            print("  Aby kontynuowac mimo to: dodaj flage --allow-wifi")
            print("  (np. dla testu loopback/dry-run --listen)")
            sys.exit(2)
        elif not args.yes:
            try:
                ans = input("\nNa pewno wyslac przez WiFi? [t/N]: ").strip().lower()
            except EOFError:
                ans = 'n'
            if ans not in ('t', 'tak', 'y', 'yes'):
                print("Anulowano. Bezpieczne zakonczenie.")
                sys.exit(0)

    # SAFETY 2: Czy 192.168.1.1 odpowiada (= dzialajacy router NIE cegla!)
    if not args.unicast and not args.yes:
        print("[CHECK] Sprawdzam czy 192.168.1.1 odpowiada na ping...")
        if router_is_alive('192.168.1.1', timeout_ms=500):
            print("")
            print("!!! " + "=" * 56 + " !!!")
            print("!!! UWAGA: 192.168.1.1 ODPOWIADA NA PING!             !!!")
            print("!!! " + "=" * 56 + " !!!")
            print("  To znaczy ze pod tym IP DZIALA jakis router")
            print("  (np. Twoj domowy Funbox/Orange/Livebox).")
            print("")
            print("  Router-cegla WS7200 w trybie upgrade NIE odpowiada na ping!")
            print("  Jezeli 192.168.1.1 odpowiada -> jestes podpiety do INNEGO routera.")
            print("")
            print("  Pakiety multicast bedzie dostawal TEN dzialajacy router,")
            print("  a NIE Twoj brick. To NIE WYRZADZI mu szkody (inny protokol),")
            print("  ale i NIE pomoze cegle.")
            print("")
            print("  Co zrobic:")
            print("   1. Odepnij kabel Ethernet od domowego routera")
            print("   2. Wepnij go bezposrednio w router-cegle (LAN port)")
            print("   3. Wlacz cegle z trzymanym przyciskiem H (tryb upgrade)")
            print("   4. Sprawdz: 'ping 192.168.1.1' powinien NIE odpowiadac")
            print("      (router-cegla w trybie upgrade nie ma stack TCP/IP)")
            print("")
            try:
                ans = input("Naprawde wyslac mimo to? [t/N]: ").strip().lower()
            except EOFError:
                ans = 'n'
            if ans not in ('t', 'tak', 'y', 'yes'):
                print("Anulowano. Bezpieczne zakonczenie.")
                sys.exit(0)
        else:
            print("[CHECK]   192.168.1.1 nie odpowiada - dobrze, prawdopodobnie router-cegla w trybie upgrade.")

    use_multicast = args.unicast is None
    dest_ip = args.unicast if args.unicast else args.multicast_ip

    mut = MUT(
        firmware_path=args.firmware,
        ini_path=args.ini,
        pc_ip=args.pc_ip,
        dest_ip=dest_ip,
        port=args.port,
        interval_ms=args.interval,
        use_multicast=use_multicast,
        ttl=args.ttl,
        verbose=args.verbose,
        log_hex=args.hex,
        listen=args.listen,
        max_passes=args.passes,
    )

    print("=" * 60)
    print("  Python MUT (replika HuaweiMUT.exe)")
    print("=" * 60)
    print(f"  Firmware:     {args.firmware}")
    print(f"  Size:         {mut.file_size:,} bytes")
    print(f"  CRC32:        0x{mut.firmware_crc:08X} ({mut.firmware_crc})")
    print(f"  INI:          {args.ini}")
    print(f"  PACKAGE_ID:   {mut.package_id}")
    print(f"  PRODUCT_ID:   {mut.product_id}")
    print(f"  Partitions:   {len(mut.partitions)}")
    for p in mut.partitions:
        print(f"    - {p['name']:12s} 0x{p['start']:08X}-0x{p['end']:08X}  {p['flag']}")
    print(f"  PC IP:        {args.pc_ip}")
    print(f"  Dest IP:      {dest_ip} ({'multicast' if use_multicast else 'UNICAST!'})")
    print(f"  Port:         {args.port}")
    print(f"  Interval:     {args.interval} ms")
    if args.listen:
        print(f"  Listen:       YES (recvfrom)")
    print("=" * 60)
    print()

    # Estimate
    chunks = (mut.file_size + CHUNK_SIZE - 1) // CHUNK_SIZE
    pass_time_s = chunks * args.interval / 1000.0
    print(f"  Spodziewana 1 runda: {chunks} chunkow x {args.interval}ms = ~{pass_time_s:.0f}s ({pass_time_s/60:.1f} min)")
    print(f"  Naciśnij CTRL+C aby przerwac.")
    print()

    try:
        mut.send_loop()
    except KeyboardInterrupt:
        pass
    finally:
        print()
        print("=" * 60)
        print(f"  Passes:       {mut.passes_completed}")
        print(f"  Packets:      {mut.packets_sent}")
        print(f"  Bytes sent:   {mut.bytes_sent:,} ({mut.bytes_sent/1024/1024:.2f} MB)")
        if args.listen:
            print(f"  Responses:    {len(mut.responses)}")
            for ts, addr, data in mut.responses[:5]:
                print(f"    {addr}: {len(data)} bytes - {data[:32].hex()}")
        print("=" * 60)


if __name__ == '__main__':
    main()
